### ISSUE TITLE
Especificaciones SGE

### ISSUE THREAD

**Issue by miguelangelronda** [jbenrui/fitness-gym#1]
Hola! no has indicado cómo vas a integrar los requisitos del módulo de Sistemas de Gestión Empresarial.

**Comment by jbenrui** [comment]
Si, realmente no lo tengo muy claro y queria preguntarle como debo hacerlo, si en la misma aplicacion o deberia ser aparte, y para exportar los datos deberia hacerlo desde la misma base de datos o crear una funcion propia en mi aplicacion que exporte los datos

**Comment by miguelangelronda** [comment]
Puede ser aparte. Descargar datos (CSV o JSON), manipularlos con Pandas y crear un nuevo fichero que le sirva de entrada a PowerBI. Con mencionar algo así en el anteproyecto es suficiente.

**Comment by jbenrui** [comment]
Okey, me pondré manos a la obra

**Comment by jbenrui** [comment]
Ya lo hemos añadido

**Comment by miguelangelronda** [comment]
gracias!
